//
//  EventDef.h
//  buyu_simple
//
//  Created by ff on 15/11/20.
//
//

#ifndef buyu_simple_EventDef_h
#define buyu_simple_EventDef_h

#define LOAD_LOGIN_UPDATE_EVENT "updateLoginLoad"
#define LOGIN_FAILED "loginFailed"

#define GOLD_START_ROLL "goldStartRoll"
#define GOLD_OPEN_BOX "goldOpenBox"
#define UPDATE_GOLD_RUNNER_EVENT "updateGoldRunner"
#define UPDATE_GOLD_STAGE_EVENT "updateGoldStage"
#define UPDATE_GOLD_DIFF_EVENT "updateGoldDiff"
#define LOAD_GOLD_UPDATE_EVENT "updateGoldLoad"
#define GOLD_RESULT "goldGameResult"

#define SHAKE_SCREEN "shakescreen"
#define CLICK_SCREEN "clickscreen"
#define OUT_OF_SCREEN "outofscreen"
#define PLIERS_ACTION_OVER "pliersactionover"
#define PILERS_BOMB "pliersbomb"
#define ARRIVE_HOME "arrivehome"
#define FIND_SOMETHING "findsomething"
#define PLIERS_FIND_THING "pliersfindthing"

#define ADD_BOMB "addbomb"
#define ADD_KEY "addkey"

#define CHANGE_PLIERS_ACTION "changepliersaction"

#define CREATE_FISH "createfish"
#define CLICK_CREATE_FISH "clickcreatefish"
#define SCHEDULE_TIDE "scheduletide"
#define TIDE_TIP "tidecometip"
#define BOSS_TIP "bosscometip"
#define TIDE_SWITCH "tideswitchbg"
#define HERO_FIRE "herofire"
#define CREATE_BULLET "createbullet"
#define CREATE_CANNON "createcannon"
#define CHANGE_CANNON "changecannon"
#define CHANGE_CANNON_MULTIPLY "changecannonmultiply"
#define HIT_FISHES "hitfishes"
#define RAY_HIT_FISHES "rayhitfishes"
#define BOMB_FISHES "bombfishes"
#define BULLET_HIT  "bullethit"
#define CAST_NET    "castnet"
#define AUTO_FIRE   "startautofire"
#define STOP_AUTO   "stopautofire"
#define STOP_AUTO_CIRCLE "stopautocircle"
#define ADD_COIN    "addfishcoin"
#define ICE_SCREEN  "icescreen"
#define FROZEN_SCREEN "frozenscreen"
#define UNFROZEN_SCREEN "unfrozenscreen"
#define CLEAR_LOCK_FISH "clearlockfish"
#define TRACE_LOCK_FISH "tracelockfish"
#define STOP_LOCK_FIRE "stoplockfire"
#define START_RUSH_FIRE "startrushfire"
#define END_RUSH_FIRE "endrushfire"
#define START_AUTO_CIRCLE "startautocircle"
#define READY_RAY_FIRE "readyrayfire"
#define UI_READY_RAY "uireadyray"
#define UI_END_RAY "uiendray"
#define RAY_ATTACK "rayattack"
#define END_RAY_FIRE "endrayfire"

#define READY_PLANE_BOMB "readyplanebomb"
#define END_PLANE_BOMB "endplanebomb"
#define UI_READY_PLANE "uireadyplane"
#define UI_END_PLANE "uiendplane"
#define PLANE_ATTACK "planeattack"

#define UI_SPLASH_NIUNIU "uisplashniuniu"
#define UI_ENTER_NIUNIU "uienterniuniu"
#define UI_SHOW_HAND "uishowhand"
#define UI_HIDE_NIUNIU "uihideniuniu"

#define UI_SPLASH_MARY "uisplashmary"
#define UI_ENTER_MARY "uientermary"
#define UI_MARY_INIT "uimaryinit"
#define UI_HIDE_MARY "uihidemary"

#define UI_ENTER_LUCKY_DRAW "uienterluckydraw"
#define UI_EXIT_LUCKY_DRAW "uiexitluckydraw"
#define UI_UPDATE_LUCKY_DRAW "uiupdateluckydraw"
#define UI_ENTER_LOTTERY "uienterlottery"
#define UI_END_LOTTERY "uiendlottery"

#define UI_UNLOCK_CANNON_LEVEL "uiunlockcannonlevel"
#define UI_UPDATE_CANNON_LEVEL "uiupdatecannonlevel"
#define UI_HIDE_CANNON_LEVEL "uihidecannonlevel"
#define UI_SHOW_CANNON_UNLOCK_DIALOG "uishowcannonunlockdialog"
#define UI_CHARGE_UNLOCK_LEVEL "uichargeunlocklevel"
#define UI_HIDE_UNLOCK_LEVEL "uihideunlocklevel"
#define UI_SHOW_SETTING "uishowsetting"
#define UI_HIDE_SETTING "uihidesetting"
#define UI_SHOW_FISH_SETTING "uishowfishsetting"
#define UI_SHOW_CANNON_SETTING "uishowcannonsetting"
#define UI_UPDATE_CANNON_SETTING "uiupdatecannonsetting"
#define UI_MULTIPLY_NOT_ENOUGH "uimultiplynotenough"
#define UI_HIDE_MULTIPLY_NOT_ENOUGH "uihidemultiplynotenough"
#define UI_LACK_GOLD_TIP "uilackgoldtip"

#define UI_UPDATE_RELIFE_BUTTON "uirelifebutton"
#define UI_UPDATE_STAR_BOX "uiupdateboxstar"
#define UI_UPDATE_GOLD "uiupdategold"
#define UI_UPDATE_DIAMOND "uiupdatediamond"
#define UI_UPDATE_ENERGY "uiupdateenergy"
#define UI_UPDATE_HEADINFO "uiupdateheadinfo"
#define UI_UPDATE_BOSS_TASK "uiupdatebosstask"
#define UI_INIT_BOSS_TASK "uiinitbosstask"
#define UI_COMP_BOSS_TASK "uicompbosstask"
#define UI_NEXT_STAGE_DIALOG "uinextstagedialog"
#define UI_INIT_TASK "uiinittask"
#define UI_UPDATE_TASK "uiupdatetask"
#define UI_SHOW_TASK_BOUND "uishowtaskbound"
#define UI_TAKE_TASK_BOUND "uitaketaskbound"
#define UI_HIDE_TASK_BOUND "uihidetaskbound"
#define UI_COMP_SUB_TASK "uicompsubtask"
#define UI_LEVELUP_TIP "uileveluptip"
#define UI_UNLOCK_TIP "uiunlocktip"
#define UI_KILLBOSS_TIP "uikillbosstip"
#define UI_UPDATE_SKILL_COUNT "uiupdateskillcount"
#define UI_USE_SKILL "uiuseskill"
#define UI_SKILL_CHARGE "uiskillcharge"
#define UI_CHARGE_USE_SKILL "uichargeuseskill"
#define UI_DISABLE_SKILL_TIP "uidisableskilltip"

#define UI_UPDATE_LOAD_STAGE "uiupdateloadstage"
#define UI_SHOW_DIARY "uishowdiary"
#define UI_DROP_ITEM "uidropitem"

#define UI_SHOW_HALL_RECHARGE "uishowhallrecharge"
#define UI_SHOW_VIP_INTRO "uishowvipintro"
#define UI_SHOW_VIP_GIFT "uishowvipgift"
#define UI_SHOW_RAY_NEED_VIP_TIP "uishowrayneedviptip"
#define UI_SHOW_AUTO_FIRE_NEED_VIP_TIP "uishowautofireneedviptip"
#define UI_SHOW_BOMB_NEED_UNLOCK_TIP "uishowbombneedunlocktip"
#define UI_SHOW_UNLOCK_NEED_DIAMOND_TIP "uishowunlockneedunlocktip"

#define UI_CAN_USE_AUTO_FIRE "uicanuseautofire"
#define UI_UPDATE_HALL_MONEY "uiupdatehallmoney"
#define UI_RECHARGE_OK "uirechargeok"
#define UI_RECHARGE_GOLD_OK "uirechargegoldok"
#define UI_RECHARGE_DIAMOND_OK "uirechargediamondok"
#define UI_CLOSE_RECHARGE "uicloserecharge"

#define UI_SHOW_BENEFITS "uishowbenefits"
#define UI_CASH_BENEFIT_CODE "uicashbenefitcode"

#define UI_SHOW_SHARE "uishowshare"
#define UI_UPDATE_SHARE_RESULT "uiupdateshareresult"
#define UI_TAKE_SHARE_COUNT_BOUND "uitakesharecountbound"
#define UI_SHOW_EVALUATE "uishowevaluate"
#define JNI_RECHARGE_OK "jnirechargeok"
#endif
